// <auto-generated />
using System;
using Integrator.Data;
using Integrator.Models.Domain.Address;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Integrator.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Integrator.Models.Domain.Address.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AddressID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressType");

                    b.Property<string>("AreaCode");

                    b.Property<string>("City");

                    b.Property<int>("CountryID");

                    b.Property<int>("IntegratorUserID")
                        .HasColumnName("IntegratorUserID");

                    b.Property<string>("Suburb");

                    b.HasKey("Id");

                    b.HasIndex("CountryID");

                    b.HasIndex("IntegratorUserID");

                    b.ToTable("Addresses");

                    b.HasDiscriminator<int>("AddressType");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IntegratorRoleID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("IntegratorRoles");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IntegratorRoleClaimID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId")
                        .HasColumnName("BIntegratorRoleID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("IntegratorRoleClaims");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IntegratorUserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("IntegratorUsers");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IntegratorUserClaimID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId")
                        .HasColumnName("IntegratorUserID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IntegratorUserClaims");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserLogin", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId")
                        .HasColumnName("IntegratorUserID");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("IntegratorUserLogins");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("IntegratorUserID");

                    b.Property<int>("RoleId")
                        .HasColumnName("IntegratorRoleID");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("IntegratorUserRoles");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("IntegratorUserID");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("IntegratorUserTokens");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Common.Country.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Integrator.Models.test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("testitem");

                    b.HasKey("Id");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("Integrator.Models.Domain.Address.ComplexAddress", b =>
                {
                    b.HasBaseType("Integrator.Models.Domain.Address.Address");

                    b.Property<string>("ComplexName");

                    b.Property<string>("ComplexUnitNumber");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Address.POBoxAddress", b =>
                {
                    b.HasBaseType("Integrator.Models.Domain.Address.Address");

                    b.Property<string>("POBoxNumber");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Address.StreetAddress", b =>
                {
                    b.HasBaseType("Integrator.Models.Domain.Address.Address");

                    b.Property<string>("StreetName");

                    b.Property<string>("StreetNumber");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Address.Address", b =>
                {
                    b.HasOne("Integrator.Models.Domain.Common.Country.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Integrator.Models.Domain.Authentication.IntegratorUser", "IntegratorUser")
                        .WithMany()
                        .HasForeignKey("IntegratorUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorRoleClaim", b =>
                {
                    b.HasOne("Integrator.Models.Domain.Authentication.IntegratorRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserClaim", b =>
                {
                    b.HasOne("Integrator.Models.Domain.Authentication.IntegratorUser", "IntegratorUser")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserLogin", b =>
                {
                    b.HasOne("Integrator.Models.Domain.Authentication.IntegratorUser", "IntegratorUser")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserRole", b =>
                {
                    b.HasOne("Integrator.Models.Domain.Authentication.IntegratorRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Integrator.Models.Domain.Authentication.IntegratorUser", "IntegratorUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Integrator.Models.Domain.Authentication.IntegratorUserToken", b =>
                {
                    b.HasOne("Integrator.Models.Domain.Authentication.IntegratorUser", "IntegratorUser")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
